---
title: "Placebo Metaanalysis: Conditioning"
output:
  html_notebook:
    fig_width: 12
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

# Analysis of behavioral data

### Load data

```{r}
library(ggplot2)
require(lmPerm)
require(boot)
require(boot.pval)
data=read.csv("simple_zerocon/table_nonan2.csv", header=T)
studies=read.csv("simple_zerocon/df_studies.csv", header=T)
# these are excluded due to insufficient data for controlling placebo magnitude within participant
studies=studies[studies$study_ID != "kessner",]
studies=studies[studies$study_ID != "ruetgen",]
studies=studies[studies$study_ID != "wager04a_princeton",]
studies=studies[studies$study_ID != "wager04b_michigan",]
#print(colnames(design))
#print(colnames(studies))


# for reproducibiliy
set.seed(2023) 
```

### behavioral PA :

```{r}

summary(lm(data=data, Rating_diff ~ Conditioning * Rating_pain_ctr  + Age + Male))

func = function(data, idx){
coef(lm(data=design[idx,], Rating_diff ~  Conditioning * Rating_pain_ctr  + Age + Male))
}
B = boot(data, func, R=5000)
print('Conditioning')
print(boot.ci(B,index=2,type="perc", conf = 0.95))
print(boot.pval(B, index=2))
print('Interaction')
print(boot.ci(B,index=6,type="perc", conf = 0.95))
print(boot.pval(B, index=6))
```

# Mean pain reduction

```{r}
mean_inst = mean(data$Rating_diff[data$Conditioning=="suggestions"])
mean_cond = mean(data$Rating_diff[data$Conditioning=="suggestions & conditioning"])

print(c('mean (INST))', mean_inst))
print(c('mean (COND-INST))', mean_cond))
print(c('difference', mean_cond - mean_inst))
```

```{r}
ggplot(data=design, aes(x=Study_ID, y=Rating_diff))+
  geom_hline(yintercept=0, linetype="dashed", alpha=0.5)+
  #geom_dotplot(aes(fill=Conditioning), binaxis='y', stackdir='center',stackratio=1, dotsize=0.5, alpha=0.8)+
  facet_wrap(~ Conditioning, scales = 'free_x')+
  stat_summary(aes(color=Conditioning), fun.data=data_summary, geom="pointrange", position = position_nudge(x = 0.3))+
   geom_jitter(height=0, width=0.1, alpha=0.2)+
  theme_bw()+
  ylab("Rating difference (placebo-ctr)")+theme(axis.text.x = element_text(angle = 90))+theme(legend.position = "none")
```


